# -*- coding: utf-8 -*-
'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.'''

a = 1
b = 2
f = []
while b <= 4000000: # Kiem tra dieu kien gia tri lon nhat trong day < 4000000
    a, b = b, a + b # Tao gia tri fibonacci su dung de quy
    if not a % 2: # Kiem tra gia tri chan
        f.append(a) # Tao day cac gia tri chan

print sum(f)
